Feature/air2204 4 personal schedule
AIR-FOI-HR/AIR2204 pull request #5
Opened 2022-12-04 15:59 UTC by karlo-rusovan

https://air2204.atlassian.net/browse/AIR2204-4

2022-12-06 13:40 UTC, DreamAgencyGithub requested changes

2022-12-06 13:40 UTC, DreamAgencyGithub commented on lib/Utilities/utils.dart
> +  static final messengerKey = GlobalKey<ScaffoldMessengerState>();
U PR za autentikaciju sam ovo spomenuo, koristite `ScaffoldMessenger.of(context)` umjesto keya

2022-12-06 13:40 UTC, DreamAgencyGithub commented on lib/application/presentation/personal_schedule.dart
> +class PersonalSchedule extends StatefulWidget {
![simulator_screenshot_BC66C36C-6F61-4ABE-90AB-F1725350E00C](https://user-images.githubusercontent.com/113169253/205922041-500a9649-2e2e-4e95-92c9-f9962c3a16c9.png)
Brand new account, dobijem ovu grešku. Također, ispis greške i buttona bi trebalo biti centrirano. Isto vrijedi i za ostale ekrane.


Također u konzoli dobijem ovo:
`════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown while applying parent data.:
Incorrect use of ParentDataWidget.

The ParentDataWidget Expanded(flex: 1) wants to apply ParentData of type FlexParentData to a RenderObject, which has been set up to accept ParentData of incompatible type BoxParentData.

Usually, this means that the Expanded widget has the wrong ancestor RenderObjectWidget. Typically, Expanded widgets are placed directly inside Flex widgets.
The offending Expanded is currently placed inside a Center widget.

The ownership chain for the RenderObject that received the incompatible parent data was:
  Column ← Expanded ← Center ← RetryButton ← BlocListener<SavedScheduleCubit, SavedScheduleState> ← BlocBuilder<SavedScheduleCubit, SavedScheduleState> ← Column ← KeyedSubtree-[GlobalKey#7b686] ← _BodyBuilder ← MediaQuery ← ⋯
When the exception was thrown, this was the stack`

Pogledajte si RetryButton widget. Parent Expanded ili Flexible widgetu mora biti: Row, Column ili Flex widget

2022-12-06 13:40 UTC, DreamAgencyGithub commented on lib/application/logic/saved_schedule_state.dart
> +
Dodajte si ovdje poseban konstruktor tipa `SavedScheduleState.initial()` pa onda stavite da taj konstruktor uvijek returna ono što koristite u Cubitu kao počeno stanje i što u Cubitu unutar `readAllSavedItems` metode prvo emitate.

2022-12-06 13:40 UTC, DreamAgencyGithub commented on lib/application/logic/saved_schedule_cubit.dart
> +      emit(SavedScheduleState(
![image](https://user-images.githubusercontent.com/113169253/205924657-c20e06f9-74f9-4e4d-90c8-879afbd53db4.png)
Ako si niste stavili ovu ekstenziju za VsCode, stavite si je. Onda si uz pomoć nje izgenerirajte copyWith metodu.
I onda kod ovog emita si napravite ovako:
`emit(state.copyWith(allDates: dates, savedItems: data, scheduleItems: dataFiltered, loading: false, currentDate: currentDate));`

2022-12-06 13:40 UTC, DreamAgencyGithub commented on lib/application/logic/saved_schedule_cubit.dart
> +      emit(SavedScheduleState(
Ista stvar kao u prethodnom komentaru, samo si emitajte ovako:
`emit(state.copyWith(error: e));`

2022-12-06 13:40 UTC, DreamAgencyGithub commented on lib/domain/repositories/saved_schedule_repository.dart
> +    final docRef = firestore.collection(MyCollections.savedItems).doc(FirebaseAuth.instance.currentUser!.uid);
Stavite da `SavedRepository` ima dependency na `FirebaseAuth`

2022-12-06 13:40 UTC, DreamAgencyGithub commented on lib/domain/repositories/saved_schedule_repository.dart
> +    final docRef = firestore.collection('savedItems').doc(FirebaseAuth.instance.currentUser!.uid);
Mislim da u `MyCollections` imate `savedItems` već?

2022-12-06 13:40 UTC, DreamAgencyGithub commented on lib/domain/repositories/saved_schedule_repository.dart
> +    DocumentReference<Map<String, dynamic>> savedItemsQuery;
Ova varijabla može biti definirana unutar for petlje?

2022-12-06 13:40 UTC, DreamAgencyGithub commented on lib/domain/repositories/saved_schedule_repository.dart
> +    ScheduleItem savedItem;
ova također

2022-12-07 17:33 UTC, karlo-rusovan commented on lib/application/presentation/personal_schedule.dart
> +class PersonalSchedule extends StatefulWidget {
fixed, retry button je sada centriran i ne daje exception.

2022-12-14 16:22 UTC, merged